using System.Text.RegularExpressions;
using KoSpellCheck.Core.ProjectConventions.Models;
using KoSpellCheck.Core.ProjectConventions.Utils;

namespace KoSpellCheck.Core.ProjectConventions.Scanning;

public sealed class ProjectConventionSymbolExtractor
{
    private static readonly Regex CSharpTypeRegex =
        new(@"\b(?:public|private|protected|internal|sealed|abstract|static|partial|readonly|unsafe|new|ref|file|record|class|interface|enum|struct|\s)+\b(class|interface|enum|record|struct)\s+([A-Za-z_][A-Za-z0-9_]*)",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

    private static readonly Regex TsTypeRegex =
        new(@"\b(?:export|default|declare|abstract|const|type|class|interface|enum|\s)+\b(class|interface|enum|type)\s+([A-Za-z_][A-Za-z0-9_]*)",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

    private static readonly Regex NamespaceRegex =
        new(@"\bnamespace\s+([A-Za-z_][A-Za-z0-9_.]*)\s*[;{]", RegexOptions.Compiled | RegexOptions.CultureInvariant);

    private static readonly Regex AutoGeneratedRegex =
        new(@"<auto-generated|@generated|generated code", RegexOptions.Compiled | RegexOptions.CultureInvariant | RegexOptions.IgnoreCase);

    public ProjectFileFacts Extract(string workspaceRoot, string absolutePath, string content)
    {
        var relativePath = ConventionPathUtils.NormalizeRelativePath(workspaceRoot, absolutePath);
        var folderPath = ConventionNamingUtils.NormalizeFolderKey(Path.GetDirectoryName(relativePath) ?? ".");
        var fileName = Path.GetFileName(absolutePath);
        var extension = Path.GetExtension(fileName).TrimStart('.').ToLowerInvariant();
        var fileStem = Path.GetFileNameWithoutExtension(fileName);
        var folderSegments = folderPath == "."
            ? new List<string>()
            : folderPath.Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries).ToList();

        var namespaceValue = ExtractNamespace(content);
        var types = ExtractTypes(content, extension);
        var primaryType = SelectPrimaryType(fileStem, types);

        var generated = Regex.IsMatch(fileName, "\\.(g|g\\.i|generated|designer|gen)\\.", RegexOptions.IgnoreCase) ||
                        folderSegments.Any(segment => Regex.IsMatch(segment, "^(obj|bin|generated|gen)$", RegexOptions.IgnoreCase)) ||
                        AutoGeneratedRegex.IsMatch(content);

        var testFile =
            folderSegments.Any(segment => Regex.IsMatch(segment, "^(test|tests|spec|specs)$", RegexOptions.IgnoreCase)) ||
            Regex.IsMatch(fileName, "\\b(test|tests|spec)\\b", RegexOptions.IgnoreCase);

        return new ProjectFileFacts
        {
            WorkspaceRoot = workspaceRoot,
            AbsolutePath = absolutePath,
            RelativePath = relativePath,
            FolderPath = folderPath,
            FolderSegments = folderSegments,
            FileName = fileName,
            FileStem = fileStem,
            Extension = extension,
            Namespace = namespaceValue,
            Types = types,
            PrimaryType = primaryType,
            IsGenerated = generated,
            IsTestProjectFile = testFile,
        };
    }

    private static string? ExtractNamespace(string content)
    {
        var match = NamespaceRegex.Match(content);
        if (!match.Success)
        {
            return null;
        }

        return match.Groups[1].Value.Trim();
    }

    private static IList<TypeSymbolFacts> ExtractTypes(string content, string extension)
    {
        var regex = extension is "ts" or "tsx" or "js" or "jsx"
            ? TsTypeRegex
            : CSharpTypeRegex;

        var output = new List<TypeSymbolFacts>();
        var seen = new HashSet<string>(StringComparer.Ordinal);

        foreach (Match match in regex.Matches(content))
        {
            if (!match.Success)
            {
                continue;
            }

            var rawKind = match.Groups[1].Value.Trim().ToLowerInvariant();
            var name = match.Groups[2].Value.Trim();
            var nameIndex = match.Groups[2].Index;
            if (name.Length == 0)
            {
                continue;
            }

            var key = $"{rawKind}:{name}:{nameIndex}";
            if (!seen.Add(key))
            {
                continue;
            }

            // Keep location on the symbol token itself so host adapters can underline/rename the type name.
            var (line, column) = OffsetToLineColumn(content, nameIndex);
            output.Add(new TypeSymbolFacts
            {
                Name = name,
                Kind = NormalizeKind(rawKind),
                Line = line,
                Column = column,
            });
        }

        return output;
    }

    private static (int line, int column) OffsetToLineColumn(string content, int offset)
    {
        if (offset <= 0)
        {
            return (0, 0);
        }

        var line = 0;
        var column = 0;
        for (var i = 0; i < content.Length && i < offset; i++)
        {
            if (content[i] == '\n')
            {
                line++;
                column = 0;
            }
            else
            {
                column++;
            }
        }

        return (line, column);
    }

    private static ConventionTypeKind NormalizeKind(string value)
    {
        return value switch
        {
            "class" => ConventionTypeKind.Class,
            "interface" => ConventionTypeKind.Interface,
            "enum" => ConventionTypeKind.Enum,
            "record" => ConventionTypeKind.Record,
            "struct" => ConventionTypeKind.Struct,
            "type" => ConventionTypeKind.Type,
            _ => ConventionTypeKind.Unknown,
        };
    }

    private static TypeSymbolFacts? SelectPrimaryType(string fileStem, IList<TypeSymbolFacts> types)
    {
        if (types.Count == 0)
        {
            return null;
        }

        var exact = types.FirstOrDefault(entry => string.Equals(entry.Name, fileStem, StringComparison.Ordinal));
        return exact ?? types[0];
    }
}
